### ISSUE TITLE
PrepareCondition parameter outcomeSlotCount should be u8

### ISSUE THREAD

**Issue by fleupold** [gnosis/conditional-tokens-contracts#82]
https://github.com/gnosis/conditional-tokens-contracts/blob/dfd903a2dda1b361e908bed01b42deadd70aa808/contracts/ConditionalTokens.sol#L64

is here a reason that parameter is not of type u8? This would enforce the <256 requirement without having to read the comment or an extra require statement.

**Comment by cag** [comment]
Yes, it actually supports up to 256 outcome slots, which is one more than the max value of a uint8. I could make it a uint16, but then I'd just be doing two bounds checks on the input, including the one done by the compiler.
